//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balcao.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Balcao.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _21botaoAjuda {
            get {
                object obj = ResourceManager.GetObject("21botaoAjuda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _21botaoCalculadora {
            get {
                object obj = ResourceManager.GetObject("21botaoCalculadora", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _21botaoCancelaCupom {
            get {
                object obj = ResourceManager.GetObject("21botaoCancelaCupom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _21botaoCancelaItem {
            get {
                object obj = ResourceManager.GetObject("21botaoCancelaItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _21botaoCliente {
            get {
                object obj = ResourceManager.GetObject("21botaoCliente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _21botaoDesconto {
            get {
                object obj = ResourceManager.GetObject("21botaoDesconto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _21botaoEncerraVenda {
            get {
                object obj = ResourceManager.GetObject("21botaoEncerraVenda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _21botaoGaveta {
            get {
                object obj = ResourceManager.GetObject("21botaoGaveta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _21botaoMenuFiscal {
            get {
                object obj = ResourceManager.GetObject("21botaoMenuFiscal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _21botaoMenuOperacoes {
            get {
                object obj = ResourceManager.GetObject("21botaoMenuOperacoes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _21botaoMenuPrincipal {
            get {
                object obj = ResourceManager.GetObject("21botaoMenuPrincipal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _21botaoPesquisa {
            get {
                object obj = ResourceManager.GetObject("21botaoPesquisa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _21botaoSair {
            get {
                object obj = ResourceManager.GetObject("21botaoSair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrowleft_green16 {
            get {
                object obj = ResourceManager.GetObject("arrowleft_green16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrowright_green16 {
            get {
                object obj = ResourceManager.GetObject("arrowright_green16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botaoAjuda {
            get {
                object obj = ResourceManager.GetObject("botaoAjuda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botaoCalculadora {
            get {
                object obj = ResourceManager.GetObject("botaoCalculadora", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botaoCancelaCupom {
            get {
                object obj = ResourceManager.GetObject("botaoCancelaCupom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botaoCancelaItem {
            get {
                object obj = ResourceManager.GetObject("botaoCancelaItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botaoCliente {
            get {
                object obj = ResourceManager.GetObject("botaoCliente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botaoDesconto {
            get {
                object obj = ResourceManager.GetObject("botaoDesconto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botaoEncerraVenda {
            get {
                object obj = ResourceManager.GetObject("botaoEncerraVenda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botaoGaveta {
            get {
                object obj = ResourceManager.GetObject("botaoGaveta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botaoMenuFiscal {
            get {
                object obj = ResourceManager.GetObject("botaoMenuFiscal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botaoMenuOperacoes {
            get {
                object obj = ResourceManager.GetObject("botaoMenuOperacoes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botaoMenuPrincipal {
            get {
                object obj = ResourceManager.GetObject("botaoMenuPrincipal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botaoPesquisa {
            get {
                object obj = ResourceManager.GetObject("botaoPesquisa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botaoSair {
            get {
                object obj = ResourceManager.GetObject("botaoSair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnLocalizar05 {
            get {
                object obj = ResourceManager.GetObject("btnLocalizar05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancelar16 {
            get {
                object obj = ResourceManager.GetObject("cancelar16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap confirmar16 {
            get {
                object obj = ResourceManager.GetObject("confirmar16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Login2 {
            get {
                object obj = ResourceManager.GetObject("Login2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaCadeadoFechado01 {
            get {
                object obj = ResourceManager.GetObject("telaCadeadoFechado01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaCarrinho02 {
            get {
                object obj = ResourceManager.GetObject("telaCarrinho02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaChave06 {
            get {
                object obj = ResourceManager.GetObject("telaChave06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaDinheiro01 {
            get {
                object obj = ResourceManager.GetObject("telaDinheiro01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaDinheiro03 {
            get {
                object obj = ResourceManager.GetObject("telaDinheiro03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaDinheiro05 {
            get {
                object obj = ResourceManager.GetObject("telaDinheiro05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaDocumento04 {
            get {
                object obj = ResourceManager.GetObject("telaDocumento04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaDocumento07 {
            get {
                object obj = ResourceManager.GetObject("telaDocumento07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaExcluirProduto {
            get {
                object obj = ResourceManager.GetObject("telaExcluirProduto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaHomem09 {
            get {
                object obj = ResourceManager.GetObject("telaHomem09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaLupa06 {
            get {
                object obj = ResourceManager.GetObject("telaLupa06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaMesclar01 {
            get {
                object obj = ResourceManager.GetObject("telaMesclar01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaMonitor04 {
            get {
                object obj = ResourceManager.GetObject("telaMonitor04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaNotaFiscal {
            get {
                object obj = ResourceManager.GetObject("telaNotaFiscal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaPrint09 {
            get {
                object obj = ResourceManager.GetObject("telaPrint09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaRegistradora01 {
            get {
                object obj = ResourceManager.GetObject("telaRegistradora01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaRelatorio01 {
            get {
                object obj = ResourceManager.GetObject("telaRelatorio01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaRelatorio02 {
            get {
                object obj = ResourceManager.GetObject("telaRelatorio02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaSair01 {
            get {
                object obj = ResourceManager.GetObject("telaSair01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telaUsuarioSenha01 {
            get {
                object obj = ResourceManager.GetObject("telaUsuarioSenha01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
